language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
    - development
    - coverity_scan
before_script:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.4 clang-3.4-doc libclang-common-3.4-dev libclang-3.4-dev libclang1-3.4 libclang1-3.4-dbg libllvm-3.4-ocaml-dev libllvm3.4 libllvm3.4-dbg llvm-3.4 llvm-3.4-dev llvm-3.4-doc llvm-3.4-examples llvm-3.4-runtime clang-modernize-3.4 clang-format-3.4 python-clang-3.4 
  - sudo ln -s /usr/bin/llvm-config-3.4 /usr/bin/llvm-config
  - sudo ln -s /usr/bin/llvm-mc-3.4 /usr/bin/llvm-mc
  - sudo ln -s /usr/bin/llvm-as-3.4 /usr/bin/llvm-as
  - sudo ln -s /usr/bin/llvm-dis-3.4 /usr/bin/llvm-dis
  - sudo ln -s /usr/bin/llc-3.4 /usr/bin/llc
  - sudo ln -s /usr/include/llvm-3.4 /usr/include/llvm
script:
  autoreconf && ./configure --enable-cppunit && make && make tests


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SUt+ULcl/cjlD38ZzAc7EdQ8cm0DADhyDmukH4F6is+36u/eeYA7bdYS8RAEKFdk2/8A/yNKhl4Q8wmgMKwIpMT8HEDu69eXh7YjW7vy/V+AoL5XhFDuxeR9XuwoYdgBC2rbGhGTF8ygXbrkNtiUkI9VhmI2hYWStMXLYW6hsT0="

addons:
  coverity_scan:
    project:
      name: "cpichard/fission"
      description: "submitted via travis"
    notification_email: pichard.cyril@laposte.net
    build_command_prepend: "autoreconf; ./configure --enable-cppunit"
    build_command: "make; make tests"
    branch_pattern: coverity_scan
