language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
    - development
before_script:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.4 clang-3.4-doc libclang-common-3.4-dev libclang-3.4-dev libclang1-3.4 libclang1-3.4-dbg libllvm-3.4-ocaml-dev libllvm3.4 libllvm3.4-dbg llvm-3.4 llvm-3.4-dev llvm-3.4-doc llvm-3.4-examples llvm-3.4-runtime clang-modernize-3.4 clang-format-3.4 python-clang-3.4 
  - sudo ln -s /usr/bin/llvm-config-3.4 /usr/bin/llvm-config
  - sudo ln -s /usr/bin/llvm-mc-3.4 /usr/bin/llvm-mc
  - sudo ln -s /usr/bin/llvm-as-3.4 /usr/bin/llvm-as
  - sudo ln -s /usr/bin/llvm-dis-3.4 /usr/bin/llvm-dis
  - sudo ln -s /usr/bin/llc-3.4 /usr/bin/llc
  - sudo ln -s /usr/include/llvm-3.4 /usr/include/llvm
script:
  autoreconf && ./configure --enable-cppunit && make && make tests
