%module fission
%include "../engine/Context.i"
%include "../engine/Engine.i"
%include "../engine/NodeCollection.i"
%include "../engine/Status.i"
%include "../graph/Name.i"
%include "../graph/Node.i"
%include "../graph/Parameter.i"
%include "../nodes/GLDisplay.i"
